version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        logger:
          files:
            - '!**/pkg/logutils/**.go'
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log.
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package.
            - pkg: github.com/instana/testify
              desc: It's a fork of github.com/stretchr/testify.
    dupl:
      threshold: 100
    errorlint:
      asserts: false
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - paramTypeCombine
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    govet:
      enable:
        - nilness
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    misspell:
      locale: US
      ignore-rules:
        - importas
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - lll
          - mnd
        path: (.+)_test\.go
      - linters:
          - staticcheck
        path: pkg/golinters/errcheck/errcheck.go
        text: 'SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead'
      - linters:
          - staticcheck
        path: pkg/golinters/errcheck/errcheck.go
        text: 'SA1019: errCfg.Ignore is deprecated: use ExcludeFunctions instead'
      - linters:
          - staticcheck
        path: pkg/golinters/govet/govet.go
        text: 'SA1019: cfg.CheckShadowing is deprecated: the linter should be enabled inside Enable.'
      - linters:
          - staticcheck
        path: pkg/golinters/godot/godot.go
        text: 'SA1019: settings.CheckAll is deprecated: use Scope instead'
      - linters:
          - staticcheck
        path: pkg/goformatters/gci/gci.go
        text: 'SA1019: settings.LocalPrefixes is deprecated: use Sections instead.'
      - linters:
          - staticcheck
        path: pkg/golinters/gofumpt/gofumpt.go
        text: 'SA1019: settings.LangVersion is deprecated: use the global `run.go` instead.'
      - linters:
          - gocritic
        path: pkg/golinters/unused/unused.go
        text: 'rangeValCopy: each iteration copies 160 bytes \(consider pointers or indexing\)'
      - linters:
          - gosec
        path: test/bench/bench_test.go
        text: 'G115: integer overflow conversion uint64 -> int'
    paths:
      - pkg/goanalysis/runner_checker.go
      - test/testdata_etc
      - internal/go
      - internal/x
      - pkg/goformatters/gci/internal
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - pkg/goanalysis/runner_checker.go
      - test/testdata_etc
      - internal/go
      - internal/x
      - pkg/goformatters/gci/internal
      - third_party$
      - builtin$
      - examples$
